#!/usr/bin/env python3
"""Generate Kamalen GTK colors and skin materials without replacing user CSS."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import tempfile

IMPORTS = ('@import url("kamalen-colors.css");', '@import url("kamalen-material.css");')


def color_css(p: dict[str, str]) -> str:
    names = {
        "accent_color": p["accent"], "accent_bg_color": p["accent"], "accent_fg_color": p["bg"],
        "destructive_color": p["red"], "success_color": p["green"], "warning_color": p["yellow"],
        "window_bg_color": p["bg"], "window_fg_color": p["fg"], "view_bg_color": p["surface"],
        "view_fg_color": p["fg"], "headerbar_bg_color": p["surface"], "headerbar_fg_color": p["fg"],
        "popover_bg_color": p["surface"], "popover_fg_color": p["fg"], "card_bg_color": p["surface"],
        "card_fg_color": p["fg"], "borders": p["dim"],
    }
    return "\n".join(f"@define-color {name} {value};" for name, value in names.items()) + "\n"


def material_css(skin: str, gtk_version: int, p: dict[str, str]) -> str:
    dropdown = "dropdown" if gtk_version == 4 else "combobox"
    if skin == "aqua-2009":
        return f"""/* Generated by Kamalen Shell: aqua-2009. */
.background, view, list {{ color: {p['fg']}; background-color: {p['bg']}; }}
.card, popover contents, notebook > header > tabs > tab {{
  border-radius: 10px;
  color: {p['fg']};
  background-color: {p['surface']};
  background-image:
    repeating-linear-gradient(to bottom, alpha({p['fg']}, 0.035) 0px, alpha({p['fg']}, 0.035) 1px, alpha({p['bg']}, 0.025) 1px, alpha({p['bg']}, 0.025) 3px),
    linear-gradient(to bottom, alpha({p['fg']}, 0.18), alpha({p['surface']}, 0.02) 46%, alpha({p['bg']}, 0.2));
  border: 1px solid {p['dim']};
  box-shadow: inset 0 1px alpha({p['fg']}, 0.3), inset 0 -1px alpha({p['bg']}, 0.42), 0 2px 6px alpha({p['bg']}, 0.28);
}}
button, entry, spinbutton, {dropdown} {{
  border-radius: 10px;
  min-height: 36px;
  color: {p['fg']};
  background-color: {p['surface']};
  background-image:
    repeating-linear-gradient(to bottom, alpha({p['fg']}, 0.04) 0px, alpha({p['fg']}, 0.04) 1px, transparent 1px, transparent 3px),
    linear-gradient(to bottom, alpha({p['fg']}, 0.28), alpha({p['surface']}, 0.03) 48%, alpha({p['bg']}, 0.24));
  border: 1px solid {p['dim']};
  box-shadow: inset 0 1px alpha({p['fg']}, 0.42), inset 0 -1px alpha({p['bg']}, 0.42), 0 1px 2px alpha({p['bg']}, 0.32);
}}
button:hover {{ border-color: {p['accent']}; box-shadow: inset 0 1px alpha({p['fg']}, 0.52), 0 0 4px alpha({p['accent']}, 0.32); }}
button:active, button:checked {{
  background-image: linear-gradient(to bottom, alpha({p['bg']}, 0.24), alpha({p['accent']}, 0.18));
  box-shadow: inset 0 2px 3px alpha({p['bg']}, 0.48), inset 0 -1px alpha({p['fg']}, 0.2);
}}
button:focus, entry:focus, spinbutton:focus, {dropdown}:focus {{ outline: 2px solid {p['accent']}; outline-offset: 1px; }}
scale trough, progressbar trough {{
  border-radius: 10px; min-height: 9px; background: {p['bg']};
  border: 1px solid {p['dim']}; box-shadow: inset 0 2px 3px alpha({p['bg']}, 0.62), inset 0 -1px alpha({p['fg']}, 0.18);
}}
scale highlight, progressbar progress {{
  border-radius: 10px; min-height: 9px;
  background-image: linear-gradient(to bottom, alpha({p['fg']}, 0.3), {p['accent']} 48%, alpha({p['bg']}, 0.2));
  box-shadow: inset 0 1px alpha({p['fg']}, 0.35);
}}
scale slider {{
  border-radius: 10px; min-width: 19px; min-height: 19px; background: {p['surface']};
  background-image: linear-gradient(to bottom, alpha({p['fg']}, 0.42), alpha({p['bg']}, 0.18));
  border: 1px solid {p['dim']}; box-shadow: inset 0 1px alpha({p['fg']}, 0.45), 0 2px 3px alpha({p['bg']}, 0.45);
}}
switch {{ border-radius: 10px; min-width: 46px; min-height: 25px; background: {p['bg']}; border: 1px solid {p['dim']}; box-shadow: inset 0 2px 3px alpha({p['bg']}, 0.55); }}
switch:checked {{ background: {p['accent']}; }}
switch slider {{ border-radius: 10px; min-width: 19px; min-height: 19px; background: {p['surface']}; border: 1px solid {p['dim']}; box-shadow: inset 0 1px alpha({p['fg']}, 0.5), 0 1px 3px alpha({p['bg']}, 0.5); }}
scrollbar slider {{ border-radius: 10px; background: {p['surface']}; border: 1px solid {p['dim']}; min-width: 12px; min-height: 12px; box-shadow: inset 0 1px alpha({p['fg']}, 0.32); }}
"""

    if skin == "skeuos-workshop":
        wood = f"mix(mix({p['bg']}, {p['yellow']}, 0.42), {p['red']}, 0.08)"
        paper = f"mix(mix({p['surface']}, {p['fg']}, 0.26), {p['yellow']}, 0.12)"
        metal = f"mix({p['surface']}, {p['dim']}, 0.38)"
        leather = f"mix({p['bg']}, {p['red']}, 0.08)"
        return f"""/* Generated by Kamalen Shell: skeuos-workshop. */
.background {{
  color: {p['fg']}; background-color: {wood};
  background-image:
    radial-gradient(ellipse at 72% 18%, transparent 0px, transparent 18px, alpha({p['bg']}, 0.16) 19px, transparent 22px),
    linear-gradient(to right, alpha({p['bg']}, 0.14), transparent 20%, alpha({p['yellow']}, 0.045) 48%, transparent 76%, alpha({p['bg']}, 0.12)),
    repeating-linear-gradient(2deg, alpha({p['bg']}, 0.12) 0px, alpha({p['bg']}, 0.12) 1px, transparent 1px, transparent 16px);
}}
view, list, treeview.view, textview text, iconview {{
  color: {p['fg']}; background-color: {paper};
  background-image: repeating-linear-gradient(0deg, alpha({p['yellow']}, 0.035) 0px, alpha({p['yellow']}, 0.035) 1px, transparent 1px, transparent 12px);
}}
.card, popover contents, notebook > header > tabs > tab {{
  border-radius: 5px;
  color: {p['fg']};
  background-color: {paper};
  background-image:
    radial-gradient(circle at 18% 24%, alpha({p['fg']}, 0.08) 0px, alpha({p['fg']}, 0.08) 1px, transparent 2px),
    repeating-linear-gradient(0deg, alpha({p['yellow']}, 0.045) 0px, alpha({p['yellow']}, 0.045) 1px, alpha({p['bg']}, 0.018) 1px, alpha({p['bg']}, 0.018) 12px);
  border: 1px solid {p['dim']};
  box-shadow: inset 1px 1px alpha({p['fg']}, 0.28), inset -1px -1px alpha({p['bg']}, 0.5), 0 3px 7px alpha({p['bg']}, 0.38);
}}
button, spinbutton, {dropdown} {{
  border-radius: 5px;
  min-height: 36px;
  color: {p['fg']};
  background-color: {metal};
  background-image:
    repeating-linear-gradient(to bottom, alpha({p['fg']}, 0.04) 0px, alpha({p['fg']}, 0.04) 1px, transparent 1px, transparent 3px),
    linear-gradient(to bottom, alpha({p['fg']}, 0.24), alpha({p['surface']}, 0.02) 48%, alpha({p['bg']}, 0.3));
  border: 1px solid {p['dim']};
  border-top-color: alpha({p['fg']}, 0.52);
  border-left-color: alpha({p['fg']}, 0.45);
  border-right-color: alpha({p['bg']}, 0.68);
  border-bottom-color: alpha({p['bg']}, 0.72);
  box-shadow: inset 1px 1px alpha({p['fg']}, 0.22), inset -1px -1px alpha({p['bg']}, 0.34), 0 2px 3px alpha({p['bg']}, 0.35);
}}
entry {{
  border-radius: 5px; min-height: 36px; color: {p['fg']}; background-color: {paper};
  background-image: repeating-linear-gradient(0deg, alpha({p['yellow']}, 0.035) 0px, alpha({p['yellow']}, 0.035) 1px, transparent 1px, transparent 12px);
  border: 1px solid {p['dim']}; box-shadow: inset 1px 2px 4px alpha({p['bg']}, 0.58), inset -1px -1px alpha({p['fg']}, 0.16);
}}
button:active, button:checked {{
  background-image: linear-gradient(to bottom, alpha({p['bg']}, 0.34), alpha({p['surface']}, 0.08));
  border-top-color: alpha({p['bg']}, 0.72); border-left-color: alpha({p['bg']}, 0.68);
  border-right-color: alpha({p['fg']}, 0.45); border-bottom-color: alpha({p['fg']}, 0.52);
  box-shadow: inset 2px 2px 4px alpha({p['bg']}, 0.58);
}}
button:focus, entry:focus, spinbutton:focus, {dropdown}:focus {{ outline: 2px solid {p['accent']}; outline-offset: -3px; }}
scale trough, progressbar trough {{
  border-radius: 5px; min-height: 10px; background: {leather};
  border: 1px solid {p['dim']}; box-shadow: inset 2px 2px 4px alpha({p['bg']}, 0.65), inset -1px -1px alpha({p['fg']}, 0.18);
}}
scale highlight, progressbar progress {{
  border-radius: 5px; min-height: 10px; background: {p['accent']};
  background-image: linear-gradient(to bottom, alpha({p['fg']}, 0.28), transparent 48%, alpha({p['bg']}, 0.2));
  box-shadow: inset 0 1px alpha({p['fg']}, 0.3);
}}
scale slider {{
  border-radius: 5px; min-width: 16px; min-height: 20px; background: {metal};
  background-image: linear-gradient(to right, alpha({p['fg']}, 0.3), transparent 45%, alpha({p['bg']}, 0.28));
  border: 1px solid {p['dim']}; box-shadow: inset 1px 1px alpha({p['fg']}, 0.3), inset -1px -1px alpha({p['bg']}, 0.38), 0 2px 3px alpha({p['bg']}, 0.38);
}}
switch {{ border-radius: 5px; min-width: 46px; min-height: 26px; background: {leather}; border: 1px solid {p['dim']}; box-shadow: inset 2px 2px 4px alpha({p['bg']}, 0.64); }}
switch:checked {{ background: {p['accent']}; }}
switch slider {{ border-radius: 5px; min-width: 18px; min-height: 18px; background: {metal}; border: 1px solid {p['dim']}; box-shadow: inset 1px 1px alpha({p['fg']}, 0.35), 0 2px 3px alpha({p['bg']}, 0.42); }}
scrollbar slider {{ border-radius: 5px; background: {metal}; border: 1px solid {p['dim']}; min-width: 13px; min-height: 13px; box-shadow: inset 1px 1px alpha({p['fg']}, 0.28), inset -1px -1px alpha({p['bg']}, 0.36); }}
"""

    if skin != "commonality":
        return f"""/* Generated by Kamalen Shell: kamalen. */
button, entry, spinbutton, {dropdown} {{
  border-radius: 999px;
  min-height: 40px;
  border-width: 0;
}}
notebook > header > tabs > tab, .card, popover contents {{ border-radius: 16px; }}
scale trough, progressbar trough, scale highlight, progressbar progress {{ border-radius: 999px; min-height: 8px; }}
scale slider {{ border-radius: 999px; min-width: 18px; min-height: 18px; }}
switch, switch slider {{ border-radius: 999px; }}
"""

    light = p["fg"]
    dark = p["bg"]
    surface = p["surface"]
    accent = p["accent"]
    return f"""/* Generated by Kamalen Shell: commonality. */
button, entry, spinbutton, {dropdown}, notebook > header > tabs > tab, .card, popover contents {{
  border-radius: 0px;
  min-height: 32px;
  color: {p['fg']};
  background-color: {surface};
  background-image: linear-gradient(to bottom, alpha({light}, 0.14), alpha({dark}, 0.18));
  border: 2px solid {p['dim']};
  border-top-color: alpha({light}, 0.55);
  border-left-color: alpha({light}, 0.55);
  border-right-color: alpha({dark}, 0.72);
  border-bottom-color: alpha({dark}, 0.72);
  box-shadow: inset 1px 1px alpha({light}, 0.24), inset -1px -1px alpha({dark}, 0.32);
}}
button:active, button:checked {{
  background-image: linear-gradient(to bottom, alpha({dark}, 0.22), alpha({light}, 0.10));
  border-top-color: alpha({dark}, 0.72);
  border-left-color: alpha({dark}, 0.72);
  border-right-color: alpha({light}, 0.55);
  border-bottom-color: alpha({light}, 0.55);
}}
button:focus, entry:focus, spinbutton:focus, {dropdown}:focus {{ outline: 1px solid {accent}; outline-offset: -4px; }}
scale trough, progressbar trough {{
  border-radius: 0px; min-height: 8px; background: {dark};
  border: 2px solid {p['dim']}; box-shadow: inset 1px 1px alpha({dark}, 0.65);
}}
scale highlight, progressbar progress {{ border-radius: 0px; min-height: 8px; background: {accent}; }}
scale slider {{
  border-radius: 0px; min-width: 12px; min-height: 18px; background: {surface};
  border: 2px solid {p['dim']}; box-shadow: inset 1px 1px alpha({light}, 0.35), inset -1px -1px alpha({dark}, 0.38);
}}
switch {{ border-radius: 0px; min-width: 42px; min-height: 24px; background: {dark}; border: 2px solid {p['dim']}; }}
switch:checked {{ background: {accent}; }}
switch slider {{ border-radius: 0px; min-width: 16px; min-height: 16px; background: {surface}; border: 1px solid {p['dim']}; }}
scrollbar slider {{ border-radius: 0px; background: {surface}; border: 1px solid {p['dim']}; min-width: 12px; min-height: 12px; }}
"""


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _ensure_imports(css: str) -> str:
    generated = ("kamalen-colors.css", "kamalen-material.css", "kamalen-aesthetic.css")
    lines = [line for line in css.splitlines() if not any(name in line for name in generated)]
    body = "\n".join(lines).lstrip("\n")
    return "\n".join(IMPORTS) + "\n" + (body + "\n" if body else "")


def write_theme(base: Path, palette: dict[str, str], skin: str) -> None:
    for version in (3, 4):
        folder = base / f"gtk-{version}.0"
        folder.mkdir(parents=True, exist_ok=True)
        root = folder / "gtk.css"
        existing = root.read_text(encoding="utf-8") if root.exists() else ""
        _atomic_write(folder / "kamalen-colors.css", color_css(palette))
        _atomic_write(folder / "kamalen-material.css", material_css(skin, version, palette))
        legacy = folder / "kamalen-aesthetic.css"
        if legacy.exists():
            legacy.unlink()
        _atomic_write(root, _ensure_imports(existing))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, default=Path.home() / ".config")
    parser.add_argument("--palette-json", required=True)
    parser.add_argument("--skin", default="kamalen")
    args = parser.parse_args()
    write_theme(args.base, json.loads(args.palette_json), args.skin)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
