
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1

zoom_initial_ratio=0.82
zoom_end_ratio=1.02
fadein_begin_opacity=0.0
fadeout_begin_opacity=1.0

animation_duration_open=350
animation_duration_close=220
animation_duration_move=320
animation_duration_tag=380
animation_duration_focus=180

animation_curve_open=0.05,1.15,0.15,1.0
animation_curve_close=0.0,0.0,0.15,1.0
animation_curve_move=0.08,1.12,0.18,1.02
animation_curve_tag=0.05,1.15,0.15,1.02
animation_curve_focus=0.0,0.0,0.15,1.0
animation_curve_opafadein=0.05,1.15,0.15,1.0
animation_curve_opafadeout=0.0,0.0,0.15,1.0
