
#Colors
rootcolor=0x000000ff
bordercolor=0x665c65ff
focuscolor=0x9a855bff
urgentcolor=0xb67554ff
scratchpadcolor=0x9a855bff
globalcolor=0x9a855bff
overlaycolor=0x5ab654ff
maximizescreencolor=0xb69454ff
