
#Colors
rootcolor=0x000000ff
bordercolor=0x6b6969ff
focuscolor=0x9ba7bfff
urgentcolor=0xce928dff
scratchpadcolor=0x9ba7bfff
globalcolor=0x9ba7bfff
overlaycolor=0x8dcea0ff
maximizescreencolor=0xcec18dff
