
#Layout
new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0
circle_layout=tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller,vertical_grid,vertical_deck,right_tile,tgmix,dwindle,canvas
