
#Window Rules
windowrule=isfloating:1,width:700,height:400,appid:floatterm
windowrule=isfloating:1,width:700,height:400,appid:mpv
windowrule=animation_type_open:zoom,animation_type_close:zoom,appid:floatterm
windowrule=animation_type_open:zoom,animation_type_close:zoom,appid:mpv
